name: Run Dusk tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dusk-tests:
    name: Run Dusk tests
    
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, fileinfo
        coverage: none
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.json') }}
        
    - name: Install Composer dependencies
      run: composer update --prefer-dist --no-interaction
      

    - name: Create Database
      run: touch database/database.sqlite
    
    - name: Setup dusk/chrome
      run: vendor/bin/dusk-updater detect --no-interaction

    - name: Run Browser tests
      run: vendor/bin/phpunit --testsuite Browser
      env:
        RUNNING_IN_CI: true
